name: Convert to R15

on:
  workflow_dispatch:
    inputs:
      mesh_name:
        description: "Mesh filename inside input_meshes/ (example: model.obj). Leave empty to convert all."
        required: false
        default: ""

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install numpy Cython PyYAML Pillow
          pip install -r requirements.txt




      - name: Create output folder
        run: |
          mkdir -p output
          
      - name: Run pipeline
        run: |
          mkdir -p output
          if [ -z "${{ github.event.inputs.mesh_name }}" ]; then
            echo "No specific mesh provided. Converting all..."
            for file in tests/*; do
              filename=$(basename "$file")
              name="${filename%.*}"
              python -m scripts.run_pipeline "$file" "output/${name}_R15.glb"
            done
          else
            file="tests/${{ github.event.inputs.mesh_name }}"
            name="${{ github.event.inputs.mesh_name }}"
            name="${name%.*}"
            python -m scripts.run_pipeline "$file" "output/${name}_R15.glb"
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: r15-output
          path: output/
